### ISSUE TITLE
主页增加联系方式

### ISSUE THREAD

**Issue by siying** [avocadotoastlive/avocadotoast.live#65]
希望主页上可以找到TG群链接、email、推特和微博的地址。

**Comment by xunma** [comment]
Hi @CatChen ! First of all, great podcast!! 👏It'd be awesome if I could make a few contributions.

As I was trying to get avocado live to run locally, `yarn build` failed.  Would you mind taking a look?
Error message👇
```
➜  avocadotoast.live git:(master) yarn install
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.59s.


➜  avocadotoast.live git:(master) gst 
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean


➜  avocadotoast.live git:(master) yarn build
yarn run v1.22.4
$ eleventy
Feed download failure: Feed downloaded (https://anchor.fm/s/e3e1fd0/podcast/rss)
Feed downloaded (https://www.ximalaya.com/album/29161862.xml): 36 episodes
Feed downloaded (https://www.ximalaya.com/album/29161862.xml): 339.985ms
Feed downloaded (https://avocadotoast.typlog.io/episodes/feed.xml): 36 episodes
Feed downloaded (https://avocadotoast.typlog.io/episodes/feed.xml): 3.645s
> Assignment to constant variable.

`TypeError` was thrown:
    TypeError: Assignment to constant variable.
        at module.exports (/Users/xunma/code/OtherProjects/avocadotoast.live/_data/data.js:313:6)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async TemplateData.getDataValue (/Users/xunma/code/OtherProjects/avocadotoast.live/node_modules/@11ty/eleventy/src/TemplateData.js:329:23)
        at async TemplateData.getAllGlobalData (/Users/xunma/code/OtherProjects/avocadotoast.live/node_modules/@11ty/eleventy/src/TemplateData.js:192:18)
        at async TemplateData.getData (/Users/xunma/code/OtherProjects/avocadotoast.live/node_modules/@11ty/eleventy/src/TemplateData.js:203:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by CatChen** [comment]
@xunma Can you rebase to the latest version of the code and try again? If you still see any error, please paste the line of code the error message is referencing.

**Comment by CatChen** [comment]
Email and Telegram group links were added in #135.
